### ISSUE TITLE
1.0.3 (and earlier 1.0.1) shows same error on 3 different Macs 

### ISSUE THREAD

**Issue by atrashko** [melonproject/melon-lab#354] opened 2019-10-13 12:40 UTC
I can not use these Melon Manager Mac version [1.0.3 (and earlier 1.0.1)] to manage any funds, simply because it would not sync to show live funds. After starting the app, it tries for about a minute, after this (attached) error screen shows up saying, there are no funds available.

I wonder, why and how could this be solved (I have no network issues on this side and many kinds of crypto and ethereum based wallets, apps, etc. work fine on these Macs).

I still can log into my existing fund(s), but the app will not show any of the live parts (other funds), starting with the screen, where I have to accept conditions. Very rarely, like every 2-3 weeks I can somehow see things working, when it happens, I try to do something to my fund(s), but this is not a reliable method of using funds.

***
I did not submit this error with 1.0.1 version, because I hoped that it will be resolved in the next app version, but it simply does not work. I understand that you developers use Mac-s (as Jenna mentioned earlier), so, please, help me with this, I already missed about 3-4 months with normally using and testing my funds.

These are the Macs, I am trying with: OS-X Mojave 10.14.6, OS-X High Sierra 10.13.6 OS-X ElCaptain 10.11.6 
<img width="1136" alt="Screenshot 2019-10-13 at 14 25 51" src="https://user-images.githubusercontent.com/51297274/66715679-5b257600-edc6-11e9-807c-ed10a5ac8d7b.png">

**Comment by jennazenk** [comment] 2019-10-16 11:06
Thanks for submitting the issue. 

Are you using Frame? Frame is used to connect to the Ethereum provider, so even if you don't want to log into the fund, it has to be open and connected before you launch the app.

**Comment by jennazenk** [comment] 2019-10-16 11:12
Duplicate of #352

**Comment by fubhy** [comment] 2019-10-16 12:22
HI @atrashko can you try applying the temporary solution explained here: https://github.com/melonproject/melon-lab/issues/352#issuecomment-542664925?

**Comment by fubhy** [comment] 2019-10-17 12:34
As reported on gitter this is now fixed.

**Closed by fubhy** 2019-10-17 12:34 UTC
Labels: duplicate
